apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crisis-frontend.fullname" . }}
  labels:
{{ include "crisis-frontend.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "crisis-frontend.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "crisis-frontend.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: Australia/Brisbane
            - name: GOOGLE_MAP_API_KEY
              value: {{default "1" .Values.env.GOOGLE_MAP_API_KEY }} 
            - name: API_URL
              value: {{default "https://stagingapi.thamhoa.vn" .Values.env.API_URL }}               
            - name: siteDomain
              value: {{default "https://staging.thamhoa.vn" .Values.env.siteDomain }}               
            - name: stsAuthority
              value: {{default "https://stagingid.thamhoa.vn/" .Values.env.stsAuthority }}               
            - name: clientId
              value: {{default "portal_staging" .Values.env.clientId }} 
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          volumeMounts:
            - name:  react-config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: react-config
          configMap:
            name: react-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
