version: "3.4"
services:
    myvn-frontend:
      image: registry.innov8.team/crisis-vn/frontend:#{System.PullRequest.PullRequestNumber}#    
      build:
        context: .
        dockerfile: ./Dockerfile-Production 
      ports:
        - 4000:4000
      tty: true